# Generated by Django 4.2.27 on 2026-03-17 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autograder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='content',
            field=models.TextField(blank=True, help_text='Student submission text (code or essay)'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='source_bundle_key',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
