# Generated by Django 4.2.27 on 2026-02-05 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autograder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cwid',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
