# Generated by Django 4.2.27 on 2026-02-12 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('autograder', '0008_alter_userprofile_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('scope', models.CharField(choices=[('PERSONAL', 'Personal'), ('COURSE', 'Course'), ('GLOBAL', 'Global')], default='PERSONAL', max_length=20)),
                ('event_type', models.CharField(choices=[('CUSTOM', 'Custom'), ('EXAM', 'Exam'), ('MEETING', 'Meeting'), ('REMINDER', 'Reminder')], default='CUSTOM', max_length=20)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('all_day', models.BooleanField(default=False)),
                ('timezone', models.CharField(blank=True, default='UTC', max_length=64)),
                ('priority', models.PositiveSmallIntegerField(default=2)),
                ('is_important', models.BooleanField(default=False)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='autograder.course')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['scope', 'start_at'], name='idx_event_scope_start'), models.Index(fields=['owner', 'start_at'], name='idx_event_owner_start'), models.Index(fields=['course', 'start_at'], name='idx_event_course_start')],
            },
        ),
    ]
