# Generated by Django 4.2.28 on 2026-03-19 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autograder', '0015_alter_assignmentinstructionasset_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubricscore',
            name='submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rubric_scores', to='autograder.submission'),
        ),
        migrations.AlterField(
            model_name='rubricscore',
            name='grading_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='autograder.gradingrun'),
        ),
        migrations.AddConstraint(
            model_name='rubricscore',
            constraint=models.UniqueConstraint(fields=('submission', 'rubric_criterion'), name='uniq_submission_rubric_criterion'),
        ),
    ]
