# Generated by Django 4.2.28 on 2026-04-20 02:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('autograder', '0022_submissiondraft'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='submissiondraft',
            name='chk_submission_draft_owner',
        ),
        migrations.AlterField(
            model_name='rubricattachment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='submissiondraft',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='submissiondraft',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('user__isnull', False), ('group__isnull', True)), models.Q(('user__isnull', True), ('group__isnull', False)), _connector='OR'), name='chk_submission_draft_owner'),
        ),
    ]
