# Generated by Django 4.2.28 on 2026-04-20 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def populate_assignment_submission_modes(apps, schema_editor):
    Assignment = apps.get_model('autograder', 'Assignment')
    Assignment.objects.filter(language__isnull=False).update(submission_mode='BOTH')
    Assignment.objects.filter(language__isnull=True).update(submission_mode='UPLOAD')


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('autograder', '0024_ai_detection'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='submission_mode',
            field=models.CharField(choices=[('UPLOAD', 'Upload only'), ('WORKSPACE', 'Workspace only'), ('BOTH', 'Upload or workspace')], default='UPLOAD', max_length=20),
        ),
        migrations.RunPython(populate_assignment_submission_modes, noop_reverse),
        migrations.AlterField(
            model_name='aidetectionfinding',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='aidetectionscan',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
