# Generated by Django 4.2.28 on 2026-04-20 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


def seed_standard_rubric_templates(apps, schema_editor):
    RubricTemplate = apps.get_model('autograder', 'RubricTemplate')
    RubricTemplateVersion = apps.get_model('autograder', 'RubricTemplateVersion')
    RubricTemplateCriterion = apps.get_model('autograder', 'RubricTemplateCriterion')

    templates = [
        {
            'template_key': 'programming-assignment-standard',
            'name': 'Programming Assignment Standard',
            'description': 'Balanced rubric for correctness, requirements coverage, code quality, testing, and style.',
            'criteria': [
                {'name': 'Correctness', 'max_points': '50.00'},
                {'name': 'Requirements coverage', 'max_points': '20.00'},
                {'name': 'Code quality and readability', 'max_points': '15.00'},
                {'name': 'Testing and edge cases', 'max_points': '10.00'},
                {'name': 'Documentation and style', 'max_points': '5.00'},
            ],
        },
        {
            'template_key': 'programming-lab-standard',
            'name': 'Programming Lab Standard',
            'description': 'Quick scoring template for smaller labs focused on functionality and output fidelity.',
            'criteria': [
                {'name': 'Functionality', 'max_points': '60.00'},
                {'name': 'Output format', 'max_points': '20.00'},
                {'name': 'Code organization', 'max_points': '10.00'},
                {'name': 'Completion', 'max_points': '10.00'},
            ],
        },
        {
            'template_key': 'programming-project-milestone',
            'name': 'Programming Project Milestone',
            'description': 'Milestone-oriented rubric for larger projects where planning, implementation, and communication all matter.',
            'criteria': [
                {'name': 'Core functionality', 'max_points': '40.00'},
                {'name': 'Design and architecture', 'max_points': '20.00'},
                {'name': 'Code quality and maintainability', 'max_points': '15.00'},
                {'name': 'Testing and validation', 'max_points': '15.00'},
                {'name': 'Documentation and presentation', 'max_points': '10.00'},
            ],
        },
    ]

    for template_data in templates:
        template, created = RubricTemplate.objects.get_or_create(
            template_key=template_data['template_key'],
            defaults={
                'name': template_data['name'],
                'description': template_data['description'],
                'scope': 'SYSTEM',
            },
        )
        if not created:
            continue

        version = RubricTemplateVersion.objects.create(
            template=template,
            version_number=1,
            is_weighted=False,
        )
        for index, criterion in enumerate(template_data['criteria']):
            RubricTemplateCriterion.objects.create(
                template_version=version,
                name=criterion['name'],
                max_points=criterion['max_points'],
                weight=None,
                order_index=index,
            )
        template.active_version = version
        template.save(update_fields=['active_version'])


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('autograder', '0025_assignment_submission_mode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RubricTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('scope', models.CharField(choices=[('SYSTEM', 'Standard'), ('COURSE', 'Course')], default='COURSE', max_length=10)),
                ('template_key', models.CharField(blank=True, max_length=120, null=True, unique=True)),
            ],
            options={
                'ordering': ['name', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='RubricTemplateVersion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('is_weighted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='autograder.rubrictemplate')),
            ],
        ),
        migrations.CreateModel(
            name='RubricTemplateCriterion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('max_points', models.DecimalField(decimal_places=2, max_digits=7)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('order_index', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('template_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='autograder.rubrictemplateversion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='rubrictemplate',
            name='active_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='autograder.rubrictemplateversion'),
        ),
        migrations.AddField(
            model_name='rubrictemplate',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rubric_templates', to='autograder.course'),
        ),
        migrations.AddField(
            model_name='rubrictemplate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='rubrictemplateversion',
            constraint=models.UniqueConstraint(fields=('template', 'version_number'), name='uniq_rubric_template_version'),
        ),
        migrations.AddIndex(
            model_name='rubrictemplate',
            index=models.Index(fields=['scope', 'course'], name='idx_rubric_tpl_scope'),
        ),
        migrations.RunPython(seed_standard_rubric_templates, noop_reverse),
    ]
