# Generated by Django 4.2.28 on 2026-04-20 20:05

from decimal import Decimal, ROUND_HALF_UP

from django.db import migrations


def _to_decimal(value):
    return Decimal(str(value)).quantize(Decimal('0.01'), rounding=ROUND_HALF_UP)


def _banded_levels(max_points, *, exceeds, meets, developing, missing):
    max_value = _to_decimal(max_points)
    return [
        {
            'label': 'Exceeds expectations',
            'min_points': _to_decimal(max_value * Decimal('0.90')),
            'max_points': max_value,
            'description': exceeds,
            'order_index': 0,
        },
        {
            'label': 'Meets expectations',
            'min_points': _to_decimal(max_value * Decimal('0.75')),
            'max_points': _to_decimal(max_value * Decimal('0.89')),
            'description': meets,
            'order_index': 1,
        },
        {
            'label': 'Developing',
            'min_points': _to_decimal(max_value * Decimal('0.40')),
            'max_points': _to_decimal(max_value * Decimal('0.74')),
            'description': developing,
            'order_index': 2,
        },
        {
            'label': 'Missing or incorrect',
            'min_points': _to_decimal(0),
            'max_points': _to_decimal(max_value * Decimal('0.39')),
            'description': missing,
            'order_index': 3,
        },
    ]


STANDARD_TEMPLATE_LEVELS = {
    'programming-assignment-standard': {
        'Correctness': {
            'levels': _banded_levels(
                '50.00',
                exceeds='Implements the required behavior correctly across normal, edge-case, and failure-path inputs.',
                meets='Produces the expected results for the main workflow with only minor correctness issues.',
                developing='Parts of the solution work, but important cases fail or the output is inconsistent.',
                missing='The submission does not produce a working solution for the required problem.',
            ),
        },
        'Requirements coverage': {
            'levels': _banded_levels(
                '20.00',
                exceeds='All requested features, methods, files, and formatting requirements are present and complete.',
                meets='Most assignment requirements are complete, with only small omissions.',
                developing='Several required elements are incomplete, partially implemented, or missing.',
                missing='Major assignment requirements are not met.',
            ),
        },
        'Code quality and readability': {
            'levels': _banded_levels(
                '15.00',
                exceeds='Code is organized, readable, and easy to review with clear naming and minimal duplication.',
                meets='Code is understandable overall, though a few sections could be cleaner or easier to follow.',
                developing='Readability is uneven because of duplication, weak naming, or confusing structure.',
                missing='Code quality issues make the submission difficult to review or maintain.',
            ),
        },
        'Testing and edge cases': {
            'levels': _banded_levels(
                '10.00',
                exceeds='The solution shows clear validation of edge cases, input handling, and failure scenarios.',
                meets='Core paths are tested and some non-happy-path behavior is handled correctly.',
                developing='Testing appears limited and misses important scenarios or edge cases.',
                missing='There is little or no evidence of meaningful validation before submission.',
            ),
        },
        'Documentation and style': {
            'levels': _banded_levels(
                '5.00',
                exceeds='Formatting, comments, and documentation make the submission easy to read and evaluate.',
                meets='Style and documentation are mostly solid with only minor clarity issues.',
                developing='Documentation or style is inconsistent and leaves important details unclear.',
                missing='Style and documentation are missing or make the code difficult to follow.',
            ),
        },
    },
    'programming-lab-standard': {
        'Functionality': {
            'levels': _banded_levels(
                '60.00',
                exceeds='All lab tasks are complete and behave as intended without instructor intervention.',
                meets='The main lab workflow is complete with only minor functional gaps.',
                developing='Only part of the lab is complete or the implementation is unreliable.',
                missing='The main lab objective is not complete.',
            ),
        },
        'Output format': {
            'levels': _banded_levels(
                '20.00',
                exceeds='Program output and formatting closely match the expected result across tested cases.',
                meets='Output is mostly correct with only small formatting or presentation issues.',
                developing='Output is partially correct but inconsistent or missing important information.',
                missing='Output is incorrect, missing, or unusable for grading.',
            ),
        },
        'Code organization': {
            'levels': _banded_levels(
                '10.00',
                exceeds='Code is neatly organized with clear naming and straightforward structure.',
                meets='Code is readable overall, with a few small organization issues.',
                developing='Structure or naming makes the solution harder to follow than it should be.',
                missing='Poor organization significantly reduces readability and maintainability.',
            ),
        },
        'Completion': {
            'levels': _banded_levels(
                '10.00',
                exceeds='The full submission is complete, polished, and ready to review.',
                meets='The required deliverable is complete with only small missing details.',
                developing='The submission is partially complete or leaves important pieces unfinished.',
                missing='The submitted work is substantially incomplete.',
            ),
        },
    },
    'programming-project-milestone': {
        'Core functionality': {
            'levels': _banded_levels(
                '40.00',
                exceeds='The milestone deliverables are implemented and integrated cleanly across the main use cases.',
                meets='Most milestone functionality is complete and works for the primary workflows.',
                developing='A meaningful portion of the milestone functionality is incomplete or unstable.',
                missing='The core milestone behavior is largely unfinished or nonfunctional.',
            ),
        },
        'Design and architecture': {
            'levels': _banded_levels(
                '20.00',
                exceeds='Implementation choices are cohesive, modular, and demonstrate sound design decisions.',
                meets='Architecture is serviceable and mostly organized, though some design decisions need refinement.',
                developing='Design is inconsistent, tightly coupled, or difficult to extend safely.',
                missing='There is little evidence of workable architecture or maintainable design.',
            ),
        },
        'Code quality and maintainability': {
            'levels': _banded_levels(
                '15.00',
                exceeds='Codebase is organized for future iteration with clear structure, naming, and manageable complexity.',
                meets='Code is generally maintainable with a few rough edges that do not block continued work.',
                developing='Complexity, duplication, or weak organization will slow future progress.',
                missing='Current code quality creates major risk for continued project development.',
            ),
        },
        'Testing and validation': {
            'levels': _banded_levels(
                '15.00',
                exceeds='The milestone includes strong evidence of validation through tests, demos, or scenario coverage.',
                meets='Validation covers the important flows, even if it is not comprehensive.',
                developing='Validation is shallow, narrow, or misses important failure paths.',
                missing='There is little or no meaningful validation of the implementation.',
            ),
        },
        'Documentation and presentation': {
            'levels': _banded_levels(
                '10.00',
                exceeds='Documentation and presentation make the project easy to review, demo, and discuss.',
                meets='Documentation and presentation are sufficient for a milestone review session.',
                developing='Reviewers can understand the project only with extra explanation or missing context.',
                missing='The milestone lacks the documentation or context needed for a useful review.',
            ),
        },
    },
}


def backfill_standard_template_levels(apps, schema_editor):
    RubricTemplate = apps.get_model('autograder', 'RubricTemplate')
    RubricTemplateCriterion = apps.get_model('autograder', 'RubricTemplateCriterion')
    RubricTemplateCriterionLevel = apps.get_model('autograder', 'RubricTemplateCriterionLevel')

    for template_key, criteria_map in STANDARD_TEMPLATE_LEVELS.items():
        template = RubricTemplate.objects.filter(template_key=template_key).first()
        if not template or not template.active_version_id:
            continue

        criteria = RubricTemplateCriterion.objects.filter(template_version_id=template.active_version_id)
        for criterion in criteria:
            definition = criteria_map.get(criterion.name)
            if not definition:
                continue
            RubricTemplateCriterionLevel.objects.filter(criterion_id=criterion.id).delete()
            for level in definition['levels']:
                RubricTemplateCriterionLevel.objects.create(
                    criterion_id=criterion.id,
                    label=level['label'],
                    min_points=level['min_points'],
                    max_points=level['max_points'],
                    description=level['description'],
                    order_index=level['order_index'],
                )


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('autograder', '0028_alter_rubriccriterionlevel_created_by_and_more'),
    ]

    operations = [
        migrations.RunPython(backfill_standard_template_levels, noop_reverse),
    ]
