"""
Downloads human-written Java and Python samples from CodeSearchNet via HuggingFace.
Saves to data/raw/human/{python,java}.jsonl

Usage:
    python data/fetch_codesearchnet.py --samples 1000
"""

import argparse
import json
import random
from pathlib import Path

from datasets import load_dataset
from tqdm import tqdm

RAW_HUMAN = Path(__file__).parent / "raw" / "human"
RAW_HUMAN.mkdir(parents=True, exist_ok=True)

LANGUAGES = ["python", "java"]


def is_valid(code: str, lang: str) -> bool:
    if not code or len(code.strip()) < 50:
        return False
    if len(code) > 4000:
        return False
    # Skip auto-generated or boilerplate files
    lowered = code.lower()
    if any(marker in lowered for marker in ["auto-generated", "do not edit", "generated by"]):
        return False
    return True


def fetch(lang: str, n: int) -> list[dict]:
    print(f"\nLoading CodeSearchNet [{lang}]...")
    ds = load_dataset("code_search_net", lang, split="train", trust_remote_code=True)

    collected = []
    indices = list(range(len(ds)))
    random.shuffle(indices)

    for idx in tqdm(indices, desc=f"Filtering {lang}"):
        if len(collected) >= n:
            break
        row = ds[idx]
        code = row.get("whole_func_string") or row.get("func_code_string", "")
        if is_valid(code, lang):
            collected.append({
                "code": code,
                "language": lang,
                "label": "human",
                "source": "codesearchnet",
                "repo": row.get("repository_name", ""),
            })

    return collected


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--samples", type=int, default=1000,
                        help="Samples per language (default 1000)")
    parser.add_argument("--seed", type=int, default=42)
    args = parser.parse_args()

    random.seed(args.seed)

    for lang in LANGUAGES:
        out_path = RAW_HUMAN / f"{lang}.jsonl"
        if out_path.exists():
            print(f"{out_path} already exists, skipping. Delete to re-fetch.")
            continue

        samples = fetch(lang, args.samples)
        with open(out_path, "w") as f:
            for s in samples:
                f.write(json.dumps(s) + "\n")

        print(f"Saved {len(samples)} {lang} samples → {out_path}")


if __name__ == "__main__":
    main()
